### ISSUE TITLE
Quick question, How spotify-qt is published in snap store ?

### ISSUE THREAD

**Issue by keshavbhatt** [kraxarn/spotify-qt#76]
I saw snapcraft.yaml snap recipe in source tree and tried to build snap using it on my system. Just wanted to make an PR to improve the mouse cursor theme issue in snap app, but the build failed. 

Can you tell how it gets published in snap store ? Thanks

**Comment by kraxarn** [comment]
Thanks for letting me know. You're right, the snap build is failing, which just means that the build from snap is outdated. I'll take a look later today.

**Comment by keshavbhatt** [comment]
Here is the issue reported by snapcraft build on core18 system (18.04)
```
build/snapcraft-spotify-qt-e96874/parts/spotify-qt/src/src/spotifyapi/player.cpp:31:20: error: no match for ‘operator[]’ (operand types are ‘const QJsonDocument’ and ‘const char [8]’)
   auto items = json["devices"].toArray();
                    ^
[ 79%] Building CXX object CMakeFiles/spotify-qt.dir/src/spotifyapi/search.cpp.o
[ 80%] Building CXX object CMakeFiles/spotify-qt.dir/src/spotifyapi/tracks.cpp.o
CMakeFiles/spotify-qt.dir/build.make:1382: recipe for target 'CMakeFiles/spotify-qt.dir/src/spotifyapi/player.cpp.o' failed
make[2]: *** [CMakeFiles/spotify-qt.dir/src/spotifyapi/player.cpp.o] Error 1
```

**Comment by keshavbhatt** [comment]
Btw here(https://github.com/kraxarn/spotify-qt/pull/77) I opened a pull request that is supposed to fix Mouse Cursor theming issue if the app installed using snap packaging format.
