### ISSUE TITLE
Issue while building app : DSO missing from command line

### ISSUE THREAD

**Issue by keshavbhatt** [kraxarn/spotify-qt#24]
Am getting issue while building on Ubuntu 16.04 

`//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line`
 :(

**Comment by kraxarn** [comment]
Any reason why you are using such an old version of Ubuntu? I usually only support the latest LTS release, but it seems to also work fine on 18.04.

**Comment by keshavbhatt** [comment]
> Any reason why you are using such an old version of Ubuntu?
I have my whole development setup set on 16.04 :)
am having all the requirements to build this app according to project's Readme.

I Am trying to build with Qt 5.13

**Comment by keshavbhatt** [comment]
This specific error is something about linking something from settings.cpp according to error : 

`/usr/bin/ld: CMakeFiles/spotify-qt.dir/src/settings.cpp.o: undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.`

**Comment by keshavbhatt** [comment]
Fixed the issue by adding this `-lstdc++` linker flag.
in CMakeLists.txt added as  `set(CMAKE_CXX_STANDARD_LIBRARIES -lstdc++)`

Thank you.

**Comment by kraxarn** [comment]
Haven't really tried in older versions of CMake, just assumed it would work fine in 3.5+, so maybe something with that?
Either way, nice it worked :smile:

**Comment by keshavbhatt** [comment]
> Haven't really tried in older versions of CMake, just assumed it would work fine in 3.5+, so maybe something with that?
> Either way, nice it worked

Am using cmake version 3.5.1
